HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace Salon.Models
{
    public class Stylist
    {
        public Stylist()
        {
            this.Clients = new HashSet<StylistClient>();
        }
        public string Specialty { get; set; }
        public string Name { get; set; }
        public int StylistId {get; set; }
        public virtual ICollection<StylistClient> Clients { get; set; }

    }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Salon.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {
        private readonly SalonContext _db;
        private readonly UserManager<ApplicationUser> _userManager; 
        public ClientController(SalonContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }
        
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            var userItems = _db.Clients.Where(entry => entry.User.Id == currentUser.Id);
            return View(userItems);
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.StylistId = new SelectList(_db.Stylists,"StylistId","Name");
            ViewBag.CheckList = _db.Stylists.ToList();
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(Client client, int StylistId)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            client.User = currentUser;
            _db.Clients.Add(client);
            if (StylistId != 0)
            {
                _db.StylistClient.Add(new StylistClient() { StylistId = StylistId, ClientId = client.ClientId });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
           var thisClient = _db.Clients
           .Include(client => client.Stylists)
           .ThenInclude(client => client.Stylist)
           .FirstOrDefault(client => client.ClientId == id);
           return View(thisClient);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Client foundClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
            return View(foundClient);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Destroy(int id)
        {
            Client foundClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
            _db.Clients.Remove(foundClient);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Update(int id)
        {
            Client foundClient = _db.Clients.FirstOrDefault( client => client.ClientId == id);
            ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
            return View(foundClient);
        }
        [HttpPost, ActionName("Update")]
        public ActionResult Update(Client client, int StylistId)
        {
            if(StylistId != 0)
            {
                _db.StylistClient.Add(new StylistClient() { StylistId = StylistId, ClientId = client.ClientId});
            }
            _db.Entry(client).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult AddStylist(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            ViewBag.StylistId = new SelectList(_db.Stylists,"StylistId", "Name");
            return View(thisClient);
        }
        [HttpPost]
        public ActionResult AddStylist(Client client, int StylistId)
        {
            if (StylistId != 0)
            {
                _db.StylistClient.Add(new StylistClient() { StylistId = StylistId, ClientId = client.ClientId});
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult DeleteStylist(int joinId)
        {
            var joinEntry = _db.StylistClient.FirstOrDefault(entry=> entry.StylistClientId == joinId);
            _db.StylistClient.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Salon.Controllers
{
    public class StylistController : Controller{
        private readonly SalonContext _db;
        public StylistController(SalonContext db)
        {
            _db = db;
        }
        [HttpGet]
        public ActionResult Index()
        {
            List<Stylist> model = _db.Stylists.ToList();
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Stylist stylist)
        {
            _db.Stylists.Add(stylist);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            var thisStylist = _db.Stylists
            .Include(stylist => stylist.Clients)
            .ThenInclude(join => join.Client)
            .FirstOrDefault(stylist => stylist.StylistId == id);
            return View(thisStylist);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Stylist foundStylist = _db.Stylists.FirstOrDefault( stylist => stylist.StylistId == id);
            ViewBag.AssociatedClients = _db.Clients.ToList();
            //.Where( client => client.StylistId == id);
            return View(foundStylist);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Destroy(int id)
        {
            Stylist foundStylist = _db.Stylists.FirstOrDefault( stylist => stylist.StylistId == id);
            _db.Stylists.Remove(foundStylist);
            List<Client> foundClients = _db.Clients.ToList();
            //.Where(client => client.StylistId == id).ToList();
            foreach(Client client in foundClients)
            {
                _db.Clients.Remove(client);
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Update(int id)
        {
            Stylist foundStylist = _db.Stylists.FirstOrDefault(stylist =>stylist.StylistId == id);
            return View(foundStylist);
        }
        [HttpPost]
        public ActionResult Update(Stylist stylist)
        {
            _db.Entry(stylist).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HairSalon/Views/Stylist/Create.cshtml
@{
    Layout = "_Layout";
}
@using Salon.Models;
@model Salon.Models.Stylist;


<div class="card">
    <div class="card-body">
        <h1 class="card-title text-center">Add a New Stylist</h1>
    </div>     
</div>
<div class="card">
    <div class ="card-body">
        @using (Html.BeginForm())
        {
            @Html.LabelFor(model => model.Name)
            @Html.TextBoxFor(model => model.Name, new {@class = "form-control"})
            <br>
            @Html.LabelFor(model => model.Specialty)
            @Html.TextBoxFor(model => model.Specialty, new {@class = "form-control"})
            <br>
            <input type="submit" value="Add Stylist" class="btn button btn-success";>
        }
    </div>
</div>

HairSalon/Views/Stylist/Delete.cshtml
@{
    Layout = "_Layout";
}
@using Salon.Models;
@model Salon.Models.Stylist;

<div class="card">
    <div class="card-body">
        <h1 class="card-title text-danger text-center">Are you sure you would like to delete Stylist: @Model.Name and associated clients?</h1>
    </div>     
</div>
<div class="card">
    <div class="card-body">
        <h3>Clients:</h3>
        <ul>
            @foreach(Client client in ViewBag.AssociatedClients)
            {
                <li><h4>@client.Name</h4></li>
            }
        </ul>
    </div>
</div>
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm())
        {
            <input type="submit" value="Delete Stylist and Associated Clients" class="btn button btn-danger"/>
        }
        
    </div>     
</div>

HairSalon/Views/Stylist/Details.cshtml
@{
    Layout = "_Layout";
}
@using Salon.Models;
@model Salon.Models.Stylist;


<div class="card">
    <div class="card-body">
        <h1 class="card-title text-center">@Model.Name</h1>
        @Html.ActionLink("Update This Stylist","Update","Stylist", new {id = Model.StylistId}, new { @class = "button btn btn-info"})
        @Html.ActionLink("Delete This Stylist","Delete","Stylist", new {id = Model.StylistId}, new { @class = "button btn btn-danger"})
    </div>
        
</div>
<div class="card">
    <div class="card-body">
        <h3 class="card-title">Clients</h3>
        @if(@Model.Clients.Count == 0)
        {
            <h2><i>The Database contains no clients linked to this Stylist at this time.</i></h2>
        }
        else
        {
        <ul>
            @foreach(var join in Model.Clients)
            {
                <h2><li>@Html.ActionLink($"{join.Client.Name}, Id: {join.Client.ClientId}", "Details","Client", new { id = join.Client.ClientId}, new { @class ="index-list"})</li></h2>
            }
        </ul>
        }
    </div>
</div>

HairSalon/Views/Stylist/Index.cshtml
@{
    Layout = "_Layout";
}
@using Salon.Models;
@model List<Salon.Models.Stylist>; 

<div class="card">
    <div class="card-body">
        <h1 class="card-title text-center">Stylists</h1>
    </div>
        <a href="/Stylist/Create" class = "button btn btn-success">Add Stylist</a>
</div>
<div class="card">
    <div class="card-body">
        <h3 class="card-title">Stylists</h3>
        @if(@Model.Count == 0)
        {
            <h2><i>There are no Stylists in the Database at this time.</i></h2>
        }
        else
        {
        <ul>
            @foreach(Stylist model in Model)
            {
                <h2><li>@Html.ActionLink($"{model.Name},{model.Specialty}", "Details","Stylist", new { id = model.StylistId})</li></h2>
            }
        </ul>
        }
    </div>
</div>

HairSalon/Views/Stylist/Update.cshtml
@{
    Layout = "_Layout";
}
@using Salon.Models;
@model Salon.Models.Stylist;
<div class="card">
    <div class="card-body">
        <h1 class="card-title text-center">Update Stylist: @Model.Name</h1>
    </div>     
</div>
<div class="card">
    <div class ="card-body">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.StylistId)
            @Html.LabelFor(model => model.Name)
            @Html.TextBoxFor(model => model.Name, new {@class = "form-control"})
            @Html.LabelFor(model => model.Specialty)
            @Html.TextBoxFor(model => model.Specialty, new {@class = "form-control"})
            <br>
            <input type="submit" value="Save" class="btn button btn-info";>
        }
    </div>
</div>